// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANsLdNAgmE-62p7g610uaUxsmOX4Ge66U',
    appId: '1:847047820596:web:a3c89b20cd5a93f0ccd161',
    messagingSenderId: '847047820596',
    projectId: 'kabachok-test',
    authDomain: 'kabachok-test.firebaseapp.com',
    storageBucket: 'kabachok-test.firebasestorage.app',
    measurementId: 'G-6F2VKFWHDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAah3ZgeKsUBJNNi-RZs2P6mr4dG9_P7AE',
    appId: '1:847047820596:android:1aeb1656879ff235ccd161',
    messagingSenderId: '847047820596',
    projectId: 'kabachok-test',
    storageBucket: 'kabachok-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyWnu-DLQiTlEDrfP2ZXZpv77q3PAagTk',
    appId: '1:847047820596:ios:1338897fdf413c99ccd161',
    messagingSenderId: '847047820596',
    projectId: 'kabachok-test',
    storageBucket: 'kabachok-test.firebasestorage.app',
    iosBundleId: 'com.example.kabachokLasalsaFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyWnu-DLQiTlEDrfP2ZXZpv77q3PAagTk',
    appId: '1:847047820596:ios:1338897fdf413c99ccd161',
    messagingSenderId: '847047820596',
    projectId: 'kabachok-test',
    storageBucket: 'kabachok-test.firebasestorage.app',
    iosBundleId: 'com.example.kabachokLasalsaFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANsLdNAgmE-62p7g610uaUxsmOX4Ge66U',
    appId: '1:847047820596:web:403f24ae03152025ccd161',
    messagingSenderId: '847047820596',
    projectId: 'kabachok-test',
    authDomain: 'kabachok-test.firebaseapp.com',
    storageBucket: 'kabachok-test.firebasestorage.app',
    measurementId: 'G-8X3TJ0WC2J',
  );
}
